apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: monte-carlo-sim-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    route.openshift.io/termination: "edge"
    haproxy.router.openshift.io/timeout: 10m
    haproxy.router.openshift.io/timeout-tunnel: 0s
spec:
  rules:
    - host: {{ .Values.public_http_address }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: monte-carlo-sim-service
                port:
                  number: 80
